export enum PlausibleEvents {
  BuyMeACoffee = 'Buy Me A Coffee',
  InitialTheme = 'Initial Theme',
  ChangeTheme = 'Change Theme',
  OpenAbout = 'Open About',
  OpenImdb = 'Open IMDB',
  LoadMore = 'Load More',
  OpenDetails = 'Open Details',
  Sort = 'Sort',
  Search = 'Search',
  SetGenre = 'Set Genre',
  SetYear = 'Set Year',
  OnlyNationalOn = 'Only National On',
  OnlyNationalOff = 'Only National Off',
  AllPremiumOff = 'All Premium Off',
  AllPremiumOn = 'All Premium On',
  AllNormalChannelsOn = 'All Normal Channels On',
  AllNormalChannelsOff = 'All Normal Channels Off',
  ChannelOn = 'Channel On',
  ChannelOff = 'Channel Off',
}
